version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: kaddem_db
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: always

  app:
    image: lindazaafrani/docker:5.0.0   # Remplacer par l'image de ton Docker Hub ou celle que tu utilises
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kaddem_db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
    ports:
      - "8089:8089"
    depends_on:
      - db

volumes:
  db-data:
