services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: kaddem_db
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: always

  app:
    image: ahedgossa2024/dockerrepository:1.0.0
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kaddem_db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
    ports:
      - "8089:8089"
    depends_on:
      - db

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - /etc/prometheus:/etc/prometheus
    entrypoint: |
      sh -c 'echo "
        global:
          scrape_interval: 15s
        scrape_configs:
          - job_name: 'app'
            static_configs:
              - targets: ['app:8089']
      " > /etc/prometheus/prometheus.yml && \
      /bin/prometheus --config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - app

volumes:
  db-data:
