services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: kaddem_db
    ports:
      - "3307:3306"  # Expose le port 3306 du conteneur sur le port 3307 de l'hôte
    volumes:
      - db-data:/var/lib/mysql  # Persiste les données de la base dans le volume db-data
    restart: always

  app:
    image: ahedgossa2024/dockerrepository:1.0.0
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kaddem_db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
    ports:
      - "8089:8089"  # Expose le port 8089 du conteneur sur le même port de l'hôte
    depends_on:
      - db  # L'application dépend du service db, elle attend que db soit prêt avant de démarrer

volumes:
  db-data:  # Volume pour persister les données MySQL

      
